# Generated by Django 5.0.1 on 2024-02-03 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('category', models.CharField(choices=[('TRANSPORT', 'TRANSPORT'), ('FOOD', 'FOOD'), ('DATA', 'DATA'), ('MISCELLANEOUS', 'MISCELLANEOUS')], default='MISCELLANEOUS', max_length=255)),
                ('description', models.TextField(max_length=1024)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
