# Generated by Django 5.0.1 on 2024-02-03 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_expense_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('TRANSPORT', 'TRANSPORT'), ('FOOD', 'FOOD'), ('DATA', 'DATA'), ('MISCELLANEOUS', 'MISCELLANEOUS')], default='MISCELLANEOUS', error_messages={'invalid_choice': 'Invalid value. Choose from {EXPENSES_TYPES}'}, max_length=255),
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('category', models.CharField(choices=[('TRANSPORT', 'TRANSPORT'), ('FOOD', 'FOOD'), ('DATA', 'DATA'), ('MISCELLANEOUS', 'MISCELLANEOUS')], default='MISCELLANEOUS', error_messages={'invalid_choice': 'Invalid value. Choose from {BUDGET_TYPES}'}, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_budget', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
